### ISSUE TITLE
不升级CocoaPods的spec仓库的命令好像不对吧

### ISSUE THREAD

**Issue by westke** [ChenYilong/CYLDeallocBlockExecutor#1]
# 不升级CocoaPods的spec仓库
pod update --verbose
--verbose 是打印安装信息
--no-repo-update是不升级spec仓

**Comment by ChenYilong** [comment]
多谢提醒，已修正 ：https://github.com/ChenYilong/CYLDeallocBlockExecutor/commit/54d1c026e2193817fec9bc53ae6e668f47a8da68
