### ISSUE TITLE
对同一个对象调用 cyl_executeAtDealloc:

### ISSUE THREAD

**Issue by ourui** [ChenYilong/CYLDeallocBlockExecutor#3]
在代码不同的地方，对同一个对象调用 [xxx cyl_executeAtDealloc:^{....}]。 期望是所有传入的block在对象释放时都可以执行。 这样能达到吗？  现在的使用情况是，设置新的block时，前一个block得到了调用,这时对象并没有释放, 这时如果在里面做了removeObserver等操作时就会有潜在bug。而对象dealloc时只调用了最后一个block.

**Comment by ChenYilong** [comment]
对应的PR，已解决，先关掉了。https://github.com/ChenYilong/CYLDeallocBlockExecutor/pull/4
