### ISSUE TITLE
这似乎是一个问题

### ISSUE THREAD

**Issue by TyrantDante** [ChenYilong/CYLDeallocBlockExecutor#9]
//因为用到了dispatch_barrier_async，该函数只能搭配自定义并行队列dispatch_queue_t使用。所以不能使用：dispatch_get_global_queue
            queue = dispatch_queue_create(queueName, DISPATCH_QUEUE_SERIAL);

创建的是一个串行队列。。。

**Comment by ChenYilong** [comment]
这个不是本项目里的问题吧,你这个是我关于gcd教程里的问题吧.

**Comment by ChenYilong** [comment]
我注释写得有问题
